#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]

required_message = "MOTIVO DEL COMMIT:" 
required_message1 = "IMPLEMENTACION:" 

with open(commit_msg_filepath, 'r') as f:
    content = f.read()
    if not content.startswith(required_message):
        print("ERROR! The commit title message must start with '%s'" % required_message)
        if not required_message1 in content:
            print("ERROR! The commit content message must start with '%s'" % required_message1)
            sys.exit(1)
        else:
            sys.exit(1)
    else:
        if not required_message1 in content:
            print("ERROR! The commit content message must start with '%s'" % required_message1)
            sys.exit(1)
